### ISSUE TITLE
Expand/Include more information on how to do rke2 restore for custom clusters

### ISSUE THREAD

**Issue by mrolmedo** [rancher/rancher-docs#1246]
## Related Issues

Hi team! In our docs, when we need to proceed with an rke2 restore when all controlplanes and etcd are completely unavailable, we follow this guide:https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/restore-rancher-launched-kubernetes-clusters-from-backup#restoring-a-cluster-from-a-snapshot-when-the-controlplaneetcd-are-completely-unavailable.
Although, It might be worthy to include some more extra information

1) **Step 2**: After all etcd nodes are removed, add a new etcd node that you are planning to restore from.

Can we include that the new node has to be etcd, controlplane and worker? 
CF ==> https://support.tools/post/rke2-with-rancher-disaster-recovery/

2) **Step 3**:Restore from an etcd snapshot.
`For local snapshots, restore using the UI is not available.
In the upper right corner, click ⋮ > Edit YAML.
Define spec.cluster.rkeConfig.etcdSnapshotRestore.name as the filename of the snapshot on disk in /var/lib/rancher/<k3s/rke2>/server/db/snapshots/.`

2.1 The path, as it is a clean node, does not exist, and it has to be created manually. It might be worth including that.

2.2 Define spec.cluster.rkeConfig.etcdSnapshotRestore.name as the filename of the snapshot on disk in /var/lib/rancher/<k3s/rke2>/server/db/snapshots/.

This led to confusion many times. Usually this is included under the etcd configuration and using the entire path.  Can we include a screenshot or something like that?
<img width="568" alt="rke2-restore" src="https://github.com/rancher/rancher-docs/assets/96732346/44ebd182-97a8-411d-a0f8-717625bf1732">

Thanks for your time.

**Comment by sunilarjun** [comment]
Hello @mrolmedo! I am working on a PR to add this information and wanted to clarify the necessary YAML for the `etcdSnapshotRestore` configuration. I have as an example the following code block that could be added:

```
...
rkeConfig:
  etcdSnapshotRestore:
    name: <string> # Refers to the filename of the associated etcdsnapshot object.
    generation: <int> # Changing the generation initiates a snapshot restore.
    restoreRKEConfig: <string> # Set to either none (or empty string), all, or kubernetesVersion.
...
```

Are `generation` and `restoreRKEConfig` required for the restore, and are there any other variables needed to be set here? Any guidance much appreciated, thanks!
