### ISSUE TITLE
Baremetal anilla Kubernets HA - New 1st time Rancher setup - TLS own wildcard certificate not working

### ISSUE THREAD

**Issue by chadleywilson** [rancher/rancher-docs#1291]
Hi There

I am unable to to get teh tls certs working. Rancher web ui doesn't even pick them up.

following this link
https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/resources/add-tls-secrets

Looking in the web ui Settings -> cacerts there is nothing. ok so I am not using a cert-manager maybe that should be empty.

But if I inspect the certs of the webpage it has **dynamiclistener-ca@1715875213** as the tls cert.

Under the rancher ingress it has tls-rancher-ingress

```
kubectl -n cattle-system describe secrets tls-rancher-ingress
Name:         tls-rancher-ingress
Namespace:    cattle-system
Labels:       <none>
Annotations:  <none>

Type:  kubernetes.io/tls

Data
====
tls.crt:  7124 bytes
tls.key:  1705 bytes
```

I have tried removing and re installing the helm chart. But I can't seem to work out how to get it to use that cert.

This is what I have in the manifest for ingress. I know my certs work I am using them on several other systems

```
spec:
  tls:
    - hosts:
        - rancher.mydomain.net
      secretName: tls-rancher-ingress
  rules:
    - host: rancher.mydomain.net
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: rancher
                port:
                  number: 80
             
```
My question how do I use my own wild card cert?
