### ISSUE TITLE
RKE2 cluster templates

### ISSUE THREAD

**Issue by mrolmedo** [rancher/rancher-docs#793]
Hi team,
For RKE2 cluster templates our docs state: "In order for the chart to appear in the form for creating new clusters, the chart must have the annotation catalog.cattle.io/type: cluster-template." (https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/manage-clusters/manage-cluster-templates#adding-a-cluster-template-to-rancher). However, if these annotations are present in the chart.yaml but not present in the index.yaml file, the templates don´t show up when you want create a cluster in Rancher UI.
Should it be clarified in our doc? I´m not an expert in helm charts, and this might be inherited or deduced per self. 

For testing purpose I used https://github.com/mrolmedo/cluster-template-examples. The main branch works, but test, where annotations are comment out, does not work.
Thanks for your help.

**Comment by martyav** [comment]
@mrolmedo Do you know if this generally holds, for 2.6 and earlier? I just started a working branch to add this to 2.7

**Comment by mrolmedo** [comment]
Hi @martyav, I´ve done different tests in Rancher 2.7.5 and Rancher 2.6.10. The behavior is the same for both:

1) Harverster cluster template: 
   - Git repository: https://github.com/janeczku/harvester-rke2-cluster-template/tree/master. This chart does not have index.yaml file.
   - Rancher UI behavior: The template shows up in the Rancher UI.
2) Rancher cluster templates forked to my own repository. Branch **test**
   - Git repository: https://github.com/mrolmedo/cluster-template-examples.git
   - Index.yaml file
   
      ```
      apiVersion: v1
      entries:
      cluster-template:
      #- annotations:  
      #    catalog.cattle.io/namespace: fleet-default
      #    catalog.cattle.io/type: cluster-template
      (redacted)
     ```
   - Rancher UI behavior: The template shows up in the Rancher UI.
3 Rancher cluster templates forked to my own repository. Branch **test02**
   - Git repository: https://github.com/mrolmedo/cluster-template-examples.git
   - Index.yaml file
   
      ```
      apiVersion: v1
      entries:
      cluster-template:
      - annotations:  
      #    catalog.cattle.io/namespace: fleet-default
      #    catalog.cattle.io/type: cluster-template
      (redacted)
     ```
   - Rancher UI behavior: The template does NOT appear in the Rancher UI.
   The only difference between scenarios 2 and 3 is that in the index.yaml file, the "-annotations" is comment out.
