### ISSUE TITLE
Are `valid_chars` and `invalid_chars` really regular expressions?

### ISSUE THREAD

**Issue by lindhe** [rancher/rancher-docs#847]
It says here that `valid_chars` and `invalid_chars` are regular expressions:

https://github.com/rancher/rancher-docs/blob/bcfd5b25aa8a74f6f719949393344f32e4c322e0/versioned_docs/version-2.7/how-to-guides/new-user-guides/helm-charts-in-rancher/create-apps.md?plain=1#L120-L121

I have a hard time seeing how a regex can be used for filtering out single characters. I don't think they are regex.

Please verify if they are regex, and add an example of what they may look like.

**Comment by lindhe** [comment]
AFAICT, they have no impact. I've tried these values, and they never seem to prohibit bad input:

**`valid_chars`**

* `asdf`
* `[asdf]`

**`invalid_chars`**

* `_`
* `*_*`

**Comment by martyav** [comment]
Closing, as `valid_chars` and `invalid_chars` are not supported yet. See https://github.com/rancher/dashboard/issues/5754. Addressed in https://github.com/rancher/rancher-docs/pull/865

**Comment by ThoSap** [comment]
@lindhe today I found a working workaround to fully support any regex with `valid_chars` and not only regex character sets as it is currently intended and documented 😉

Just but your valid regex inside the following expression, the the regex will work as intended.
I have a few useful examples below.
```yaml
  - variable: app.myvariable
    label: My Variable
    description: My Variable description
    # Put your regex here   ↓ inside the parentheses ()
    valid_chars: ".]{0}^(?!()$).*|"
    # Make sure you escape any \ of your regex with \\ so we have a valid YAML and
    # remove the start '^' and end '$' of the string anchors from your original regex
```

Basically how Rancher validates `valid_chars` and `invalid_chars` inside `validateChars` function [shell/utils/validators/index.js#L96-L131](https://github.com/rancher/dashboard/blob/v2.9.2/shell/utils/validators/index.js#L96-L131) is that it creates an OR combined regex of both (meaning `/(<valid_chars>|<invalid_chars>)/g`), but with the caveat, that it **negates the expected character set** (and not a full regex) from the `valid_chars` in this line [shell/utils/validators/index.js#L104](https://github.com/rancher/dashboard/blob/v2.9.2/shell/utils/validators/index.js#L104) and creates a character set for the `invalid_chars` [shell/utils/validators/index.js#L108](https://github.com/rancher/dashboard/blob/v2.9.2/shell/utils/validators/index.js#L108) which also is not intended to accept a regex.

They are then combined as mentioned before in this line [shell/utils/validators/index.js#L112](https://github.com/rancher/dashboard/blob/v2.9.2/shell/utils/validators/index.js#L112)

Now if one of both character set expressions in the combined regex matches against the input, an error message will be displayed in the Rancher Helm UI.

To workaround this, I basically:

1. **Silenced the negating character set from line [shell/utils/validators/index.js#L104](https://github.com/rancher/dashboard/blob/v2.9.2/shell/utils/validators/index.js#L104)**
   ```js
   // ### Original generated regex ###
   // Disclaimer: ${our_valid_chars_regex} is just a placeholder an not part of the regex
   //             ↓↓↓ This capture group and negating set is added by the `validateChars` function
   const regex = /([^${our_valid_chars_regex}])/;
   //                                        ↑↑
   
   // ### Generated regex with workaround ###
   //                           ↓↓↓↓↓ closes the negating set but does not match anything due to {0}
   const regexWorkaround = /([^.]{0}${our_valid_chars_regex}|])/;
   //                                                       ↑ silences the original negating set closing bracket using a capture group OR |
   ```
2. **Put the original regex in a negative lookahead capture group**
   This basically tells the resulting regex to **NOT** match our original regex but anything else, which is what we want as the`validateChars` function variable `match` needs to be a falsy value to **NOT** display any validation errors.
   ```js
   // ### Negative lookahead capture group ###
   //                                ↓↓↓   ↓ This negative lookahead capture group tells the regex to NOT search for our original regex
   const regexWorkaround = /([^.]{0}^(?!(${our_valid_chars_regex})$).*|])/;
   //                          start↑  end↑ ↑↑match everything else
   ```

### Examples

**CPU resources**
[RegExr: Kubernetes CPU resources](https://regexr.com/875m7)
[Rancher Helm Questions.yaml: Kubernetes CPU resources](https://regexr.com/875ma)

```yaml
  - variable: app.resources.requests.cpu
    label: CPU Requests
    description: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#meaning-of-cpu
    required: true
    group: Resources
    valid_chars: ".]{0}^(?!((0|[1-9]\\d*)(\\.\\d{1,2}[1-9])?m?)$).*|"
```

**Memory resources**
[RegExr: Kubernetes MEM resources](https://regexr.com/875pj)
[Rancher Helm Questions.yaml: Kubernetes MEM resources](https://regexr.com/875pv)

```yaml
  - variable: app.resources.requests.memory
    label: Memory Requests
    description: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#meaning-of-memory
    required: true
    group: Resources
    valid_chars: ".]{0}^(?!([1-9]\\d*(Ei|Pi|Ti|Gi|Mi|Ki|E|P|T|G|M|K|[EPTGMkm]?i?))$).*|"
  - variable: app.resources.limits.memory
    label: Memory Limits
    description: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#meaning-of-memory
    required: true
    group: Resources
    valid_chars: ".]{0}^(?!([1-9]\\d*(Ei|Pi|Ti|Gi|Mi|Ki|E|P|T|G|M|K|[EPTGMkm]?i?))$).*|"
```

**Kubernetes OCI container image**
[RegExr: Kubernetes OCI image](https://regexr.com/875g1)
[Rancher Helm Questions.yaml: Kubernetes OCI image](https://regexr.com/875r6)

```yaml
  - variable: app.image
    label: OCI Container Image
    required: true
    max_length: 128
    valid_chars: ".]{0}^(?!((?:(?:[a-z0-9]+(?:[._-][a-z0-9]+)*)(?::\d{1,5})?)(?:(?:/[a-z0-9]+(?:[._-][a-z0-9]+)*)*|[a-z0-9]+(?:[._-][a-z0-9]+)*)(?::[A-Za-z0-9][A-Za-z0-9._-]*)?(?:@sha256:[a-f0-9]{64})?)$).*|"
```
