### ISSUE TITLE
In `questions.yaml`, `max_length` doesn't work.

### ISSUE THREAD

**Issue by lindhe** [rancher/rancher-docs#855]
In my testing, it seems like setting `max_length` has no effect.

I've tried this:

```yaml
questions:
  - variable: name
    group: "General"
    label: "Cluster name"
    max_length: 11
    required: true
    type: string
```

It says here that it should work:

https://github.com/rancher/rancher-docs/blob/bcfd5b25aa8a74f6f719949393344f32e4c322e0/versioned_docs/version-2.7/how-to-guides/new-user-guides/helm-charts-in-rancher/create-apps.md?plain=1#L115-L116

**Comment by brandond** [comment]
What version of the Rancher Dashboard UI are you testing this with? Can you show an example of the UI allowing an input field to be submitted with a value that violates the configured max length?

**Comment by lindhe** [comment]
I'm on v2.7.6.

I see it in the following scenario:

1.  Create an [RKE2 Cluster Template](https://ranchermanager.docs.rancher.com/v2.7/how-to-guides/new-user-guides/manage-clusters/manage-cluster-templates#rke2-cluster-template) with the following `questions.yaml`:

    ```yaml
    questions:
      - variable: cluster.name
        group: "General"
        label: "Cluster name"
        required: true
        type: string
        max_length: 5
    ```

2. Go to Cluster Management, click "Create" and select your cluster template.
3. This:

    ![image](https://github.com/rancher/rancher-docs/assets/7773090/ff5211ec-b6a6-4dc5-aebf-e818d4aaff66)

4. Clicking install will now create a cluster with `.Values.cluster.name=asdfasdfasdf`.

As you can see, there is no indication that an invalid string has been entered, and the cluster is created just fine.

Maybe related to #847 which doesn't seem to work either.

Happy to help if there is anything else I can do!

Cheers!
